import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";


import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Jongolmohol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable}  antialiased bg-[url('https://res.cloudinary.com/dg1okcxsx/image/upload/v1766676139/top-view-raw-fish-placed-ice-surrounded-with-fruit-slices_fw6dwu.jpg')] bg-cover `}
      >
        <Navbar></Navbar>
          {children}
          <Footer></Footer>
      </body>
    </html>
  );
}
